<?php
$helper = Mage::helper("eke_mouseflow");
if (!$helper->isTrackerEnabled()) {
    return;
}
$id = $helper->getTrackerId();
?>

<script type="text/javascript">
var _mfq = _mfq || [];
  (function() {
    var mf = document.createElement("script");
    mf.type = "text/javascript"; mf.async = true;
    mf.src = "//cdn.mouseflow.com/projects/<?php echo $id; ?>.js";
    document.getElementsByTagName("head")[0].appendChild(mf);
  })();
	
<?php 
	$request = $this->getRequest();
	$module = $request->getModuleName();
	$controller = $request->getControllerName();
	$action = $request->getActionName();
	
	if(Mage::registry('current_product')) { echo '_mfq.push(["setVariable", "Page", "Product"]);';	}
	
	if($controller == 'result' || $controller =='advanced') { echo '_mfq.push(["setVariable", "Page", "Search Result"]);'; }
	
	if($module == 'customer' && $controller == 'account' && $action == 'index'){ echo '_mfq.push(["setVariable", "User", "Account Registered"]);'; }
	
	if($module == 'checkout' && $controller == 'cart' && $action == 'index') {echo '_mfq.push(["setVariable", "Cart", "Added Product"]);'; }
	
	if($module == 'wishlist') {	echo '_mfq.push(["setVariable", "Wishlist", "Added"]);'; }	
	
	if($module == 'onestepcheckout' && $action == 'index') { echo '_mfq.push(["setVariable", "Checkout", "Initiate"]);'; }
	
	if($module == 'checkout' && $action == 'success') { echo '_mfq.push(["setVariable", "Checkout", "Completed"]);'; } 

?>	


</script>




